#!/bin/sh
# Copyright (C) 2015 Glen Pitt-Pladdy
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# See: https://www.pitt-pladdy.com/blog/_20150108-225857_0000_Nginx_on_Cacti_via_SNMP/

STATUSURL=http://localhost/nginx_status


curl --silent $STATUSURL \
	| sed 's/^Active connections: \([0-9]\+\) *$/\1/' \
	| grep -v '^server accepts handled requests$' \
	| sed 's/^ \([0-9]\+\) \([0-9]\+\) \([0-9]\+\) *$/\1\n\2\n\3/' \
	| sed 's/^Reading: \([0-9]\+\) Writing: \([0-9]\+\) Waiting: \([0-9]\+\) *$/\1\n\2\n\3/'

